version: "3.5"

networks:
   solarflow-net:
     name: sf_network
     driver: bridge

services:
  statuspage:
    image: rbrandstaedter/solarflow-statuspage:master
    container_name: "sf-statuspage"
    command: "--online"
    ports:
      - 5000:5000
    volumes:
      - ${PWD}/statuspage-config.ini:/config.ini
    networks: 
      - solarflow-net
    restart: "no"
    logging:
      options:
        max-size: 50m
  
  control:
    image: rbrandstaedter/solarflow-control:master
    container_name: "sf-control"
    volumes:
      - ${PWD}/control-config.ini:/config.ini
    networks: 
      - solarflow-net
    restart: "no"
    logging:
      options:
        max-size: 50m

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: "sf-mqtt"
    ports:
      - 1883:1883
    environment:
      - "PYTHONUNBUFFERED=1"
    networks: 
      - solarflow-net
    volumes:
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: "no"
    logging:
      options:
        max-size: 50m
